### ISSUE TITLE
Automated build of images

### ISSUE THREAD

**Issue by enolfc** [EGI-Federation/fedcloud-vmi-templates#41]
Add automation to build images with GitHub actions or similar tools

**Comment by brucellino** [comment]
If this is still open, I'd like to take a crack at it.

**Comment by enolfc** [comment]
This is still open, the pieces are there, we have scripts for building the image but we need a place to build them as GitHub actions runners don't support kvm. 
I started looking at self-hosted runners but still unclear about the security implications

**Comment by brucellino** [comment]
Security considerations aside, is the only constraint KVM?

**Comment by enolfc** [comment]
Now available after #76, #77, #79, #80 and #81 :)
