### ISSUE TITLE
Provide almalinux

### ISSUE THREAD

**Issue by enolfc** [EGI-Federation/fedcloud-vmi-templates#54]
# Short Description of the issue

Add Almalinux images

**Comment by sebastian-luna-valero** [comment]
FYI:
* https://appdb.egi.eu/store/vappliance/almalinux.server.9
* https://appdb.egi.eu/store/vappliance/almalinux.server.8

**Comment by sebastian-luna-valero** [comment]
As noted by @enolfc we also need to check
* https://github.com/AlmaLinux/cloud-images

**Comment by sebastian-luna-valero** [comment]
Addressed in https://github.com/EGI-Federation/fedcloud-vmi-templates/pull/91
