### ISSUE TITLE
CentOS 7 and 8 EOL

### ISSUE THREAD

**Issue by sebastian-luna-valero** [EGI-Federation/fedcloud-vmi-templates#68]
# Short Description of the issue

Check the CentOS images that we are providing:
https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/

# Summary of proposed changes

Update CentOS images accordingly

**Comment by sebastian-luna-valero** [comment]
See also https://github.com/EGI-Federation/fedcloud-vmi-templates/issues/54

**Comment by sebastian-luna-valero** [comment]
Looking at https://github.com/EGI-Federation/fedcloud-vmi-templates/blob/main/centos/appdb/centos-8.yaml
* The VMI expires on 25th April
* CentOS 8 Stream last built is scheduled on 31st May
* Is it worth updating this VMI?

Looking at https://github.com/EGI-Federation/fedcloud-vmi-templates/blob/main/centos/appdb/centos-7.yaml
* The VMI expires on 4th July
* CentOS 7 goes EOL on 30th June
* I don't think it's worth updating this VMI

Should we simply wait until these two expire and just focus on providing Alma 9?

**Comment by enolfc** [comment]
For CentOS 7, I think we don't need to build the next one.
For CentOS 8, building a new version is rather straightforward so we can do it, give it a 3 months expiry and then deprecate. If there are issues for building I would deprecate directly, no need to use effort for few months lifetime.

Summary: need to focus on Alma

**Comment by sebastian-luna-valero** [comment]
Agreed, thanks!

CentOS 8 update in https://github.com/EGI-Federation/fedcloud-vmi-templates/pull/71

**Comment by enolfc** [comment]
I think we need to do alma9 and remove centosX from the repo

**Comment by sebastian-luna-valero** [comment]
I found https://github.com/AlmaLinux/cloud-images and I can give it a go.

Should we make releases (or at least tag) + changelog in case we want to go back in time and check files for older (deleted) VMIs? (e.g. centosX)

**Comment by sebastian-luna-valero** [comment]
Along with:
* [centos-7.json](https://github.com/EGI-Federation/fedcloud-vmi-templates/blob/7f6fe98eef5140922ba635e7222ccf23a6eda7b6/centos/centos-7.json)
* [centos-8.json](https://github.com/EGI-Federation/fedcloud-vmi-templates/blob/7f6fe98eef5140922ba635e7222ccf23a6eda7b6/centos/centos-8.json)

I think we should also clean up:
* [fedcloud-appliance.json](https://github.com/EGI-Federation/fedcloud-vmi-templates/blob/7f6fe98eef5140922ba635e7222ccf23a6eda7b6/ubuntu/fedcloud-appliance.json)
* [jupyterhub-ubuntu-16.04.json](https://github.com/EGI-Federation/fedcloud-vmi-templates/blob/7f6fe98eef5140922ba635e7222ccf23a6eda7b6/ubuntu/jupyterhub-ubuntu-16.04.json)
* [ubuntu-18.04.json](https://github.com/EGI-Federation/fedcloud-vmi-templates/blob/7f6fe98eef5140922ba635e7222ccf23a6eda7b6/ubuntu/ubuntu-18.04.json)

Right?

**Comment by enolfc** [comment]
> I found https://github.com/AlmaLinux/cloud-images and I can give it a go.
> 

Yes, we are producing images for ubuntu/centos by installing the OS on a clean disk instead of extending an existing cloud-image. That can also work (and could produce smaller images) but may require a bit of customisation of the packer stuff 

> Should we make releases (or at least tag) + changelog in case we want to go back in time and check files for older (deleted) VMIs? (e.g. centosX)

+1, I will create a release so it's easy to get here.
Should we try to build _all_ images on every release?

**Comment by sebastian-luna-valero** [comment]
> Yes, we are producing images for ubuntu/centos by installing the OS on a clean disk instead of extending an existing cloud-image. 

My plan is to adapt what's in https://github.com/AlmaLinux/cloud-images to the setup here for ubuntu/centos; would that be ok?

>  Should we try to build all images on every release?

Good question but I see pros and cons, and I am not sure what would be best practice here?

**Comment by sebastian-luna-valero** [comment]
Addressed in https://github.com/EGI-Federation/fedcloud-vmi-templates/pull/91
