### ISSUE TITLE
Automatic testing of VMIs

### ISSUE THREAD

**Issue by sebastian-luna-valero** [EGI-Federation/fedcloud-vmi-templates#93]
As discussed [recently](https://github.com/EGI-Federation/fedcloud-vmi-templates/pull/73#issuecomment-2071668007) it would be nice to have an automatic way to test the VMIs built on this repository.

@enolfc proposed this initial plan:
1. Build the image as part of the action. This has been recently added in https://github.com/EGI-Federation/fedcloud-vmi-templates/pull/76 and later improved in https://github.com/EGI-Federation/fedcloud-vmi-templates/pull/79  and https://github.com/EGI-Federation/fedcloud-vmi-templates/pull/80
1. Upload the image to a site. We are building images in SCAI, should we also use the same site for testing? (image uploads are enabled in SCAI)
1. Start the image with terraform
1. Interact with the running VM; what tests would be relevant? can we do this without a public IP? (this would be very helpful also for the argo probe)
1. Destroy everything

Am I missing something?

**Comment by sebastian-luna-valero** [comment]
For the record, @brucellino also added:
> I would have typically used terratest for this - if can rely on the terraform provider, then nontrivial test cases can be written. We can easily test point 3 above by writing an inspec or testinfra compliance profile, and then using a Terraform provisioner during the test.

**Comment by sebastian-luna-valero** [comment]
Update regarding `terratest`

I am looking at https://terratest.gruntwork.io/ and the first requirement is that no need to know [Go](https://go.dev/) to write your tests.

I don't know about you guys, but at the moment that's a no-go for me? Pun intended :)

**Comment by sebastian-luna-valero** [comment]
Update: An initial testing has been added in https://github.com/EGI-Federation/fedcloud-vmi-templates/pull/94 and checked in https://github.com/EGI-Federation/fedcloud-vmi-templates/pull/98

The plan in the comment [above](https://github.com/EGI-Federation/fedcloud-vmi-templates/issues/93#issue-2497397227) has been updated as follows:
1. Build the image as part of the action. 
1. Upload the image to a site (currently TUBITAK)
1. Start the image with `im-client`
1. SSH into the VM and run `hostname`. What generic test could we add here to make it relevant?
1. Destroy everything

**Comment by enolfc** [comment]
I consider this complete now. We can improve in next releases
